# Generated by Django 4.2.23 on 2025-07-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('hod_pending', 'Pending HOD Approval'), ('hod_approved', 'HOD Approved'), ('hod_rejected', 'HOD Rejected'), ('hr_pending', 'Pending HR Approval'), ('hr_approved', 'HR Approved')], default='hod_pending', max_length=20),
        ),
    ]
