# Generated by Django 4.2.23 on 2025-07-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_alter_leaverequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('hod_pending', 'Pending from HOD'), ('hod_approved', 'HOD Approved'), ('hod_rejected', 'HOD Rejected'), ('hr_pending', 'Pending HR Approval'), ('hr_approved', 'HR Approved')], default='hod_pending', max_length=20),
        ),
    ]
