# Generated by Django 4.2.23 on 2025-07-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hodprofile',
            name='department',
        ),
    ]
